os:
  - linux
dist: trusty

sudo: false

env:
  global:
    - ENCRYPTION_LABEL: "26052853ecfe"
    - COMMIT_AUTHOR_EMAIL: "meiblorn@gmail.com"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - tree

  code_climate:
    repo_token:
      secure: cCpVDCkuWfXusQw4ePvio33Jpsprwft1JbdoGlhwXF0wIVC9YmES5Q7/aXOP2WWqxfG2Ts4peNPJHOQHZXOn0dtdIzmZQMXkbyMQomAYk6gL0+GENEtOqihCRInC4Ej+2rKsBv5xjl5WjAgc/odngMLXr2MvjRNjvZMFmuQexMv87muXdXg6cQTLVV4IqN7KaHjr4U9UZsngf/NaHUGj4qVo+kxoURAKHFMdK4LbdIfr+Vn39EWhDNUhRVehgOSH1a52xBS3o4AvsELdryqaeI6g7ZBwlVltBhKvVRsUBZJ62wmUWV6jru/v2gfBH74oT2KPqGrb2DIkodrARmZV2cvwEAV/I+6sgwWb4EvEBNAcVz/FE58ZDjF17yyC+gcMpLrJS1oleruN3bQFF3ud5W600Ql5BOjqFiMxDS9NEfGiIB7Jm0+Y2F+9ATiG1AHCm30YvaxdwQ85JwXJeslk3hG/MLQIHGUqpYL8UpscHQoIfhbssxabvZ5RyhzAPw3fLDVcMkLkJLssVunkO0Z8/Axk4r+M2gXpJxNi/uzzKNJD3yCWlV8867xbvl6a+aSfSjjxy5JFmM2OpCOnxyV4qFW98ID6DKJOL9CVO3xgCTDcWjr7YUijsQX3SSUfxbFiE8hV0gnIrE/FzCLoYGZ1hdZuqoC/eiQ5258MfplXNrM=

git:
  depth: 5

branches:
  except:
    - gh-pages

language: node_js
node_js:
  - stable

cache:
  directories:
  - "node_modules"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 10 # give xvfb some time to start

install:
  - npm install

script:
  - npm run test:ci
  - npm run build:release

after_success:
  - chmod -R a+x scripts
  - bash ./scripts/git/gh-pages.sh
  - bash ./scripts/npm/publish.sh
  - bash ./scripts/npm/codeclimate.sh
